#!/bin/sh

usage(){
	printf "radio [OPTION]\n\nOPTION:\noe1 ... play radio ö1\ndhr ... deep house radio\nnm ... nice music for nice people\naus ... stop radio\n"
	exit 1
}

while [ $# -gt 0 ]; do
	case "$1" in
		"oe1")
			printf "starting stream in background\n"
			mpv http://ors-sn04.ors-shoutcast.at/oe1-q1a </dev/null >/dev/null 2>&1 &;;
		
		"nm")	printf "starting stream in background\n"
			mpv http://167.86.93.118:8000/stream.mp3 </dev/null >/dev/null 2>&1 &;;
		
		"dhr")
			printf "starting stream in background\n"
			mpv http://62.210.105.16:7000/stream </dev/null >/dev/null 2>&1 &;;
		"aus")
			printf "radio aus\n"

			if pidof -x mpv > /dev/null
			then
				sudo kill $(ps ax| grep "[m]pv http://ors-sn04.ors-shoutcast.at/fm4-q1a" | awk '{print $1}')
			fi;;
		#fm4)
			#removed fm4 because dislike new management
			#printf "starting stream in background\n"
			#mpv http://ors-sn04.ors-shoutcast.at/fm4-q1a </dev/null >/dev/null 2>&1 &;;		
		*) usage;;
	esac
	shift
done
